name: level_data
description: Level domain for Sozzle
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies: {equatable: ^2.0.5}

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
